In [5]:
import pandas as pd
import numpy as np
from sklearn.model_selection import train_test_split
from sklearn.linear_model import LogisticRegression
from sklearn.grid_search import GridSearchCV
from sklearn.metrics import accuracy_score, confusion_matrix, f1_score
from sklearn.preprocessing import StandardScaler

In [11]:
path = r'C:\Users\Public\Documents\HRS\28.11'
beginning_of_name_EL = '\Feature matrix EL no noise'
beginning_of_name_EL_OM = '\Feature matrix EL+OM no noise'
end_of_name = 'peaks.csv'
list_of_names = [' 3 ', ' 4 ', ' 5 ', ' no 72_F75 3 ', ' no 72_F75 4 ',  ' no 72_F75 5 ']
param_grid = {'C': [1,5,10,12,15,17,18,19,20,21,22,23, 25]}
cv = 3
acc = np.zeros((6,3)) # list of accuracies, shape list_of_names*3
f1 = np.zeros((6,3)) # list of f1_scores, shape list_of_names*3
for i in range(len(list_of_names)):
    data = pd.read_csv(path + beginning_of_name_EL + list_of_names[i] + end_of_name)
    data1 = pd.read_csv(path + beginning_of_name_EL_OM + list_of_names[i] + end_of_name)
    print(i)
    
    X = data.drop('target', 1) #full of EL data ~ 900 sequencies
    y = data['target']

    X1 = data1.drop('target', 1) #full of OM data ~ 200 sequencies
    y1 = data1['target']

    X2 = data.drop('target', 1)[:np.shape(y1)[0]] #cutted EL data to the size of OM data ~ 200 sequencies
    y2 = data['target'][:np.shape(y1)[0]]

    (X_train, X_test, y_train, y_test) = train_test_split(X, y, test_size=0.3, stratify=y)
    encoder = StandardScaler()
    X_train_scaled = encoder.fit_transform(X_train)
    X_test_scaled = encoder.fit_transform(X_test)

    (X_train_1, X_test_1, y_train_1, y_test_1) = train_test_split(X1, y1, test_size=0.3, stratify=y1)
    encoder = StandardScaler()
    X_train_scaled_1 = encoder.fit_transform(X_train_1)
    X_test_scaled_1 = encoder.fit_transform(X_test_1)

    (X_train_2, X_test_2, y_train_2, y_test_2) = train_test_split(X2, y2, test_size=0.3, stratify=y2)
    encoder = StandardScaler()
    X_train_scaled_2 = encoder.fit_transform(X_train_2)
    X_test_scaled_2 = encoder.fit_transform(X_test_2)

    model = LogisticRegression(class_weight='balanced')
    optimizer = GridSearchCV(model, param_grid, cv=cv)
    optimizer.fit(X_train_scaled, y_train)

    model1 = LogisticRegression(class_weight='balanced')
    optimizer1 = GridSearchCV(model1, param_grid, cv=cv)
    optimizer1.fit(X_train_scaled_1, y_train_1)

    model2 = LogisticRegression(class_weight='balanced')
    optimizer2 = GridSearchCV(model2, param_grid, cv=cv)
    optimizer2.fit(X_train_scaled_2, y_train_2)
    
#     acc[i][0]= (accuracy_score(y_test, optimizer.best_estimator_.predict(X_test_scaled)) * 100.0)
#     acc[i][1]= (accuracy_score(y_test, optimizer.best_estimator_.predict(X_test_scaled_1)) * 100.0)
#     acc[i][2]= (accuracy_score(y_test, optimizer.best_estimator_.predict(X_test_scaled_2)) * 100.0)
    
    f1[i][0]= f1_score(y_test, optimizer.best_estimator_.predict(X_test_scaled), average ='weighted')
    f1[i][1]= f1_score(y_test_1, optimizer1.best_estimator_.predict(X_test_scaled_1), average ='weighted')
    f1[i][2]= f1_score(y_test_2, optimizer2.best_estimator_.predict(X_test_scaled_2), average ='weighted')

0
1
2
3
4
5


In [9]:
f1

array([[0.9960842 , 0.98733499, 0.9626129 ],
       [0.98853963, 0.98700892, 0.98730966],
       [1.        , 0.97364354, 0.98730966],
       [0.97831229, 0.98647901, 0.91780822],
       [0.96891125, 0.98647901, 0.96011001],
       [0.96755302, 0.98647901, 0.93351669]])

In [12]:
f1

array([[0.97734142, 0.98733499, 1.        ],
       [0.97549687, 0.96200496, 0.98730966],
       [0.98853963, 1.        , 1.        ],
       [0.97947421, 0.98647901, 0.94725336],
       [0.96891125, 1.        , 0.98644831],
       [0.9682725 , 1.        , 0.95934493]])

In [15]:
y_test_1, optimizer.best_estimator_.predict(X_test_scaled)

(91     0.0
 213    0.0
 74     0.0
 176    0.0
 46     0.0
 198    0.0
 236    0.0
 76     0.0
 159    0.0
 61     0.0
 81     0.0
 27     1.0
 199    0.0
 171    0.0
 28     1.0
 146    0.0
 157    0.0
 151    0.0
 105    0.0
 106    0.0
 233    0.0
 55     0.0
 19     1.0
 36     1.0
 43     1.0
 107    0.0
 120    0.0
 158    0.0
 239    0.0
 66     0.0
       ... 
 83     0.0
 112    0.0
 197    0.0
 56     0.0
 148    0.0
 72     0.0
 193    0.0
 57     0.0
 42     1.0
 6      1.0
 33     1.0
 138    0.0
 88     0.0
 122    0.0
 52     0.0
 217    0.0
 189    0.0
 182    0.0
 150    0.0
 45     0.0
 211    0.0
 35     1.0
 235    0.0
 23     1.0
 237    0.0
 152    0.0
 118    0.0
 220    0.0
 54     0.0
 208    0.0
 Name: target, Length: 73, dtype: float64,
 array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 1., 0., 0., 0., 0., 0., 0.,
        0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 1., 0., 1., 0., 0.,
        0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0

In [14]:
optimizer.best_estimator_.predict(X_test_scaled)

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 1., 0., 0., 0., 0., 0., 0.,
       0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 1., 0., 1., 0., 0.,
       0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
       0., 0., 0., 0., 0., 0., 0., 1., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
       0., 0., 0., 0., 1., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
       1., 0., 0., 1., 0., 0., 0., 1., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
       0., 0., 1., 0., 0., 1., 0., 0., 0., 0., 0., 0., 0., 0., 1., 0., 0.,
       0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 1., 0., 0., 0., 0., 0.,
       0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
       0., 0., 0., 0., 0., 0., 0., 0., 0., 1., 0., 0., 0., 0., 0., 1., 0.,
       0., 1., 0., 1., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
       1., 0., 0., 0., 0., 0., 1., 0., 0., 0., 0., 0., 0., 0., 1., 0., 0.,
       0., 0., 0., 0., 0., 0., 0., 1., 0., 0., 0., 0., 0., 0., 0., 0., 1.,
       0., 0., 0., 0., 0.