In [1]:
import pandas as pd
import numpy as np
from sklearn.model_selection import train_test_split
from sklearn.linear_model import LogisticRegression
from sklearn.grid_search import GridSearchCV
from sklearn.metrics import accuracy_score, confusion_matrix, f1_score
from sklearn.preprocessing import StandardScaler
import xgboost

C:\Users\User\Anaconda3\lib\site-packages\sklearn\cross_validation.py:41: DeprecationWarning: This module was deprecated in version 0.18 in favor of the model_selection module into which all the refactored classes and functions are moved. Also note that the interface of the new CV iterators are different from that of this module. This module will be removed in 0.20.
  "This module will be removed in 0.20.", DeprecationWarning)
C:\Users\User\Anaconda3\lib\site-packages\sklearn\grid_search.py:42: DeprecationWarning: This module was deprecated in version 0.18 in favor of the model_selection module into which all the refactored classes and functions are moved. This module will be removed in 0.20.
  DeprecationWarning)


In [32]:
path = r'C:\Users\Public\Documents\HRS\28.11'
beginning_of_name_EL = '\Feature matrix EL no noise'
beginning_of_name_EL_OM = '\Feature matrix EL+OM no noise'
end_of_name = 'peaks.csv'
list_of_names = [' 3 ', ' 4 ', ' 5 ', ' no 72_F75 3 ', ' no 72_F75 4 ',  ' no 72_F75 5 ']

acc = np.zeros((6,3)) # list of accuracies, shape list_of_names*3
f1 = np.zeros((6,3)) # list of f1_scores, shape list_of_names*3
for i in range(len(list_of_names)):
    data = pd.read_csv(path + beginning_of_name_EL + list_of_names[i] + end_of_name)
    data1 = pd.read_csv(path + beginning_of_name_EL_OM + list_of_names[i] + end_of_name)
    print(i)
    
    X = data.drop('target', 1) #full of EL data ~ 900 sequencies
    y = data['target']

    X1 = data1.drop('target', 1) #full of OM data ~ 200 sequencies
    y1 = data1['target']

    X2 = data.drop('target', 1)[:np.shape(y1)[0]] #cutted EL data to the size of OM data ~ 200 sequencies
    y2 = data['target'][:np.shape(y1)[0]]

    (X_train, X_test, y_train, y_test) = train_test_split(X, y, test_size=0.3, stratify=y)
    encoder = StandardScaler()
    X_train_scaled = encoder.fit_transform(X_train)
    X_test_scaled = encoder.fit_transform(X_test)

    (X_train_1, X_test_1, y_train_1, y_test_1) = train_test_split(X1, y1, test_size=0.3, stratify=y1)
    encoder = StandardScaler()
    X_train_scaled_1 = encoder.fit_transform(X_train_1)
    X_test_scaled_1 = encoder.fit_transform(X_test_1)

    (X_train_2, X_test_2, y_train_2, y_test_2) = train_test_split(X2, y2, test_size=0.3, stratify=y2)
    encoder = StandardScaler()
    X_train_scaled_2 = encoder.fit_transform(X_train_2)
    X_test_scaled_2 = encoder.fit_transform(X_test_2)

    model = xgboost.XGBClassifier()
    model.fit(X_train_scaled, y_train)

    model1 = xgboost.XGBClassifier()
    model1.fit(X_train_scaled_1, y_train_1)

    model2 = xgboost.XGBClassifier()
    model2.fit(X_train_scaled_2, y_train_2)

    y_pred = model.predict(X_test_scaled)
    predictions = [round(value) for value in y_pred]

    y_pred1 = model1.predict(X_test_scaled_1)
    predictions1 = [round(value) for value in y_pred1]

    y_pred2 = model2.predict(X_test_scaled_2)
    predictions2 = [round(value) for value in y_pred2]
    
    acc[i][0]= (accuracy_score(y_test, predictions) * 100.0)
    acc[i][1]= (accuracy_score(y_test_1, predictions1) * 100.0)
    acc[i][2]= (accuracy_score(y_test_2, predictions2) * 100.0)
    
    f1[i][0]= f1_score(y_test, predictions)
    f1[i][1]= f1_score(y_test_1, predictions1)
    f1[i][2]= f1_score(y_test_2, predictions2)
    
#     print("Accuracy for EL: %.2f%%" % (accuracy_score(y_test, predictions) * 100.0))
#     print("Accuracy for EL and OM: %.2f%%" % (accuracy_score(y_test_1, predictions1) * 100.0))
#     print("Accuracy for EL (cutted): %.2f%%" % (accuracy_score(y_test_2, predictions2) * 100.0))

0


C:\Users\User\Anaconda3\lib\site-packages\sklearn\preprocessing\label.py:151: DeprecationWarning: The truth value of an empty array is ambiguous. Returning False, but in future this will result in an error. Use `array.size > 0` to check that an array is not empty.
  if diff:
C:\Users\User\Anaconda3\lib\site-packages\sklearn\preprocessing\label.py:151: DeprecationWarning: The truth value of an empty array is ambiguous. Returning False, but in future this will result in an error. Use `array.size > 0` to check that an array is not empty.
  if diff:
C:\Users\User\Anaconda3\lib\site-packages\sklearn\preprocessing\label.py:151: DeprecationWarning: The truth value of an empty array is ambiguous. Returning False, but in future this will result in an error. Use `array.size > 0` to check that an array is not empty.
  if diff:


1


C:\Users\User\Anaconda3\lib\site-packages\sklearn\preprocessing\label.py:151: DeprecationWarning: The truth value of an empty array is ambiguous. Returning False, but in future this will result in an error. Use `array.size > 0` to check that an array is not empty.
  if diff:
C:\Users\User\Anaconda3\lib\site-packages\sklearn\preprocessing\label.py:151: DeprecationWarning: The truth value of an empty array is ambiguous. Returning False, but in future this will result in an error. Use `array.size > 0` to check that an array is not empty.
  if diff:
C:\Users\User\Anaconda3\lib\site-packages\sklearn\preprocessing\label.py:151: DeprecationWarning: The truth value of an empty array is ambiguous. Returning False, but in future this will result in an error. Use `array.size > 0` to check that an array is not empty.
  if diff:


2


C:\Users\User\Anaconda3\lib\site-packages\sklearn\preprocessing\label.py:151: DeprecationWarning: The truth value of an empty array is ambiguous. Returning False, but in future this will result in an error. Use `array.size > 0` to check that an array is not empty.
  if diff:
C:\Users\User\Anaconda3\lib\site-packages\sklearn\preprocessing\label.py:151: DeprecationWarning: The truth value of an empty array is ambiguous. Returning False, but in future this will result in an error. Use `array.size > 0` to check that an array is not empty.
  if diff:
C:\Users\User\Anaconda3\lib\site-packages\sklearn\preprocessing\label.py:151: DeprecationWarning: The truth value of an empty array is ambiguous. Returning False, but in future this will result in an error. Use `array.size > 0` to check that an array is not empty.
  if diff:


3


C:\Users\User\Anaconda3\lib\site-packages\sklearn\preprocessing\label.py:151: DeprecationWarning: The truth value of an empty array is ambiguous. Returning False, but in future this will result in an error. Use `array.size > 0` to check that an array is not empty.
  if diff:
C:\Users\User\Anaconda3\lib\site-packages\sklearn\preprocessing\label.py:151: DeprecationWarning: The truth value of an empty array is ambiguous. Returning False, but in future this will result in an error. Use `array.size > 0` to check that an array is not empty.
  if diff:
C:\Users\User\Anaconda3\lib\site-packages\sklearn\preprocessing\label.py:151: DeprecationWarning: The truth value of an empty array is ambiguous. Returning False, but in future this will result in an error. Use `array.size > 0` to check that an array is not empty.
  if diff:


4


C:\Users\User\Anaconda3\lib\site-packages\sklearn\preprocessing\label.py:151: DeprecationWarning: The truth value of an empty array is ambiguous. Returning False, but in future this will result in an error. Use `array.size > 0` to check that an array is not empty.
  if diff:
C:\Users\User\Anaconda3\lib\site-packages\sklearn\preprocessing\label.py:151: DeprecationWarning: The truth value of an empty array is ambiguous. Returning False, but in future this will result in an error. Use `array.size > 0` to check that an array is not empty.
  if diff:
C:\Users\User\Anaconda3\lib\site-packages\sklearn\preprocessing\label.py:151: DeprecationWarning: The truth value of an empty array is ambiguous. Returning False, but in future this will result in an error. Use `array.size > 0` to check that an array is not empty.
  if diff:


5


C:\Users\User\Anaconda3\lib\site-packages\sklearn\preprocessing\label.py:151: DeprecationWarning: The truth value of an empty array is ambiguous. Returning False, but in future this will result in an error. Use `array.size > 0` to check that an array is not empty.
  if diff:
C:\Users\User\Anaconda3\lib\site-packages\sklearn\preprocessing\label.py:151: DeprecationWarning: The truth value of an empty array is ambiguous. Returning False, but in future this will result in an error. Use `array.size > 0` to check that an array is not empty.
  if diff:
C:\Users\User\Anaconda3\lib\site-packages\sklearn\preprocessing\label.py:151: DeprecationWarning: The truth value of an empty array is ambiguous. Returning False, but in future this will result in an error. Use `array.size > 0` to check that an array is not empty.
  if diff:


In [27]:
acc

array([[ 99.6031746 ,  98.71794872,  96.15384615],
       [ 97.61904762, 100.        ,  98.71794872],
       [ 98.41269841,  94.87179487, 100.        ],
       [ 97.43589744,  98.63013699,  98.63013699],
       [ 99.57264957,  97.26027397, 100.        ],
       [ 97.00854701, 100.        , 100.        ]])

In [29]:
acc

array([[ 99.20634921,  98.71794872,  97.43589744],
       [ 99.6031746 ,  98.71794872,  97.43589744],
       [100.        , 100.        , 100.        ],
       [ 99.14529915,  97.26027397,  98.63013699],
       [ 99.57264957, 100.        ,  95.89041096],
       [ 98.71794872,  98.63013699,  97.26027397]])

In [33]:
acc

array([[ 98.01587302, 100.        ,  97.43589744],
       [ 97.61904762, 100.        ,  98.71794872],
       [ 99.6031746 , 100.        ,  98.71794872],
       [ 96.58119658,  98.63013699,  95.89041096],
       [ 97.43589744,  95.89041096,  97.26027397],
       [ 98.29059829, 100.        , 100.        ]])

In [34]:
f1

array([[0.82758621, 1.        , 0.9375    ],
       [0.85      , 1.        , 0.97142857],
       [0.97142857, 1.        , 0.96969697],
       [0.8       , 0.96551724, 0.89655172],
       [0.76923077, 0.88      , 0.93333333],
       [0.88888889, 1.        , 1.        ]])

In [10]:
path = r'C:\Users\Public\Documents\HRS\28.11'
data = pd.read_csv(path +'\Feature matrix EL no noise 5 peaks.csv')
data1 = pd.read_csv(path +'\Feature matrix EL+OM no noise 5 peaks.csv')

X = data.drop('target', 1)
y = data['target']

X1 = data1.drop('target', 1)
y1 = data1['target']

X2 = data.drop('target', 1)[:np.shape(y1)[0]]
y2 = data['target'][:np.shape(y1)[0]]

(X_train, X_test, y_train, y_test) = train_test_split(X, y, test_size=0.3, stratify=y)
encoder = StandardScaler()
X_train_scaled = encoder.fit_transform(X_train)
X_test_scaled = encoder.fit_transform(X_test)

(X_train_1, X_test_1, y_train_1, y_test_1) = train_test_split(X1, y1, test_size=0.3, stratify=y1)
encoder = StandardScaler()
X_train_scaled_1 = encoder.fit_transform(X_train_1)
X_test_scaled_1 = encoder.fit_transform(X_test_1)

(X_train_2, X_test_2, y_train_2, y_test_2) = train_test_split(X2, y2, test_size=0.3, stratify=y2)
encoder = StandardScaler()
X_train_scaled_2 = encoder.fit_transform(X_train_2)
X_test_scaled_2 = encoder.fit_transform(X_test_2)

model = xgboost.XGBClassifier()
model.fit(X_train_scaled, y_train)

model1 = xgboost.XGBClassifier()
model1.fit(X_train_scaled_1, y_train_1)

model2 = xgboost.XGBClassifier()
model2.fit(X_train_scaled_2, y_train_2)

y_pred = model.predict(X_test_scaled)
predictions = [round(value) for value in y_pred]

y_pred1 = model1.predict(X_test_scaled_1)
predictions1 = [round(value) for value in y_pred1]

y_pred2 = model2.predict(X_test_scaled_2)
predictions2 = [round(value) for value in y_pred2]

print("Accuracy for EL: %.2f%%" % (accuracy_score(y_test, predictions) * 100.0))
print("Accuracy for EL and OM: %.2f%%" % (accuracy_score(y_test_1, predictions1) * 100.0))
print("Accuracy for EL (cutted): %.2f%%" % (accuracy_score(y_test_2, predictions2) * 100.0))

Accuracy for EL: 96.43%
Accuracy for EL and OM: 100.00%
Accuracy for EL (cutted): 97.44%


C:\Users\User\Anaconda3\lib\site-packages\sklearn\preprocessing\label.py:151: DeprecationWarning: The truth value of an empty array is ambiguous. Returning False, but in future this will result in an error. Use `array.size > 0` to check that an array is not empty.
  if diff:
C:\Users\User\Anaconda3\lib\site-packages\sklearn\preprocessing\label.py:151: DeprecationWarning: The truth value of an empty array is ambiguous. Returning False, but in future this will result in an error. Use `array.size > 0` to check that an array is not empty.
  if diff:
C:\Users\User\Anaconda3\lib\site-packages\sklearn\preprocessing\label.py:151: DeprecationWarning: The truth value of an empty array is ambiguous. Returning False, but in future this will result in an error. Use `array.size > 0` to check that an array is not empty.
  if diff:


In [ ]:
path = r'C:\Users\Public\Documents\HRS\28.11'
beginning_of_name_EL = '\Feature matrix EL no noise'
beginning_of_name_EL_OM = '\Feature matrix EL+OM no noise'
end_of_name = 'peaks.csv'
list_of_names = [' 3 ', ' 4 ', ' 5 ', ' no 72_F75 3 ', ' no 72_F75 4 ',  ' no 72_F75 5 ']

param_grid = {'C': [1,5,10,12,15,17,18,19,20,21,22,23, 25]}
cv = 3

acc = np.zeros((6,3)) # list of accuracies, shape list_of_names*3
f1 = np.zeros((6,3)) # list of f1_scores, shape list_of_names*3

for i in range(len(list_of_names)):
    data = pd.read_csv(path + beginning_of_name_EL + list_of_names[i] + end_of_name)
    data1 = pd.read_csv(path + beginning_of_name_EL_OM + list_of_names[i] + end_of_name)
    print(i)
    
    X = data.drop('target', 1) #full of EL data ~ 900 sequencies
    y = data['target']

    X1 = data1.drop('target', 1) #full of OM data ~ 200 sequencies
    y1 = data1['target']

    X2 = data.drop('target', 1)[:np.shape(y1)[0]] #cutted EL data to the size of OM data ~ 200 sequencies
    y2 = data['target'][:np.shape(y1)[0]]

    (X_train, X_test, y_train, y_test) = train_test_split(X, y, test_size=0.3, stratify=y)
    encoder = StandardScaler()
    X_train_scaled = encoder.fit_transform(X_train)
    X_test_scaled = encoder.fit_transform(X_test)

    (X_train_1, X_test_1, y_train_1, y_test_1) = train_test_split(X1, y1, test_size=0.3, stratify=y1)
    encoder = StandardScaler()
    X_train_scaled_1 = encoder.fit_transform(X_train_1)
    X_test_scaled_1 = encoder.fit_transform(X_test_1)

    (X_train_2, X_test_2, y_train_2, y_test_2) = train_test_split(X2, y2, test_size=0.3, stratify=y2)
    encoder = StandardScaler()
    X_train_scaled_2 = encoder.fit_transform(X_train_2)
    X_test_scaled_2 = encoder.fit_transform(X_test_2)

    model = LogisticRegression(class_weight='balanced')
    optimizer = GridSearchCV(model, param_grid, cv=cv)
    optimizer.fit(X_train_scaled, y_train)

    model1 = LogisticRegression(class_weight='balanced')
    optimizer1 = GridSearchCV(model1, param_grid, cv=cv)
    optimizer1.fit(X_train_scaled_1, y_train_1)

    model2 = LogisticRegression(class_weight='balanced')
    optimizer2 = GridSearchCV(model2, param_grid, cv=cv)
    optimizer2.fit(X_train_scaled_2, y_train_2)
    
    acc[i][0]= (accuracy_score(y_test, optimizer.best_estimator_.predict(X_test_scaled)) * 100.0)
    acc[i][1]= (accuracy_score(y_test_1, optimizer1.best_estimator_.predict(X_test_scaled_1)) * 100.0)
    acc[i][2]= (accuracy_score(y_test_2, optimizer2.best_estimator_.predict(X_test_scaled_2)) * 100.0)
    
    f1[i][0]= f1_score(y_test, optimizer.best_estimator_.predict(X_test_scaled), average ='weighted')
    f1[i][1]= f1_score(y_test_1, optimizer1.best_estimator_.predict(X_test_scaled_1), average ='weighted')
    f1[i][2]= f1_score(y_test_2, optimizer2.best_estimator_.predict(X_test_scaled_2), average ='weighted')